-- Lumora database schema for Supabase (PostgreSQL).
-- Run this once in Supabase → SQL Editor. Every table is protected by Row Level Security so that
-- users can only ever read and write their own rows. IDs are generated by the client (nanoid).

create table if not exists public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade default auth.uid(),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  name text not null check (char_length(name) <= 120),
  instructions text not null default '' check (char_length(instructions) <= 8000),
  preferred_mode text,
  preferred_model text,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  project_id text references public.projects (id) on delete set null,
  title text not null default 'New chat' check (char_length(title) <= 300),
  mode text,
  model text,
  pinned boolean not null default false,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists conversations_user_updated on public.conversations (user_id, updated_at desc);

create table if not exists public.messages (
  id text primary key,
  conversation_id text not null references public.conversations (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  role text not null check (role in ('user', 'assistant')),
  content text not null default '',
  -- attachments, provider turns, tool activity, sources, model metadata
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists messages_conversation on public.messages (conversation_id, created_at);

create table if not exists public.memories (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  content text not null check (char_length(content) <= 500),
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_modes (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Metadata (and extracted text) of files attached to projects. Original binaries are not stored.
create table if not exists public.files (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  project_id text references public.projects (id) on delete cascade,
  conversation_id text references public.conversations (id) on delete cascade,
  name text not null,
  mime text not null,
  size bigint not null,
  text_content text,
  created_at timestamptz not null default now()
);

-- Read-only public snapshots created with "Share conversation".
create table if not exists public.shared_conversations (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  title text not null,
  data jsonb not null,
  created_at timestamptz not null default now()
);

-- ── Row Level Security ─────────────────────────────────────────────────────────
do $$
declare t text;
begin
  foreach t in array array['user_settings','projects','conversations','messages','memories','custom_modes','files','shared_conversations']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "own rows" on public.%I', t);
    execute format('create policy "own rows" on public.%I for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t);
  end loop;
end $$;

-- Anyone with the (unguessable) link may read a shared snapshot.
drop policy if exists "public read shared" on public.shared_conversations;
create policy "public read shared" on public.shared_conversations for select to anon, authenticated using (true);

-- Messages must belong to a conversation the user owns.
drop policy if exists "message conversation owner" on public.messages;
create policy "message conversation owner" on public.messages as restrictive for insert to authenticated
  with check (exists (select 1 from public.conversations c where c.id = conversation_id and c.user_id = (select auth.uid())));
